spring:
  application:
    name: backend
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/cement-knowledge
    username: postgres
    password: 1234
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: false
      group:
        PostgreSQL:
          include: db
          show-details: never
  health:
    defaults:
      enabled: false          # 禁用全部默认
    db:
      enabled: true           # 只开 db
rag:
  base-url: http://192.168.1.37:8000
  docs-process-path: /rag/v1/docs/process
  ingest-status-path-template: /rag/v1/ingest/{docId}/status
docs:
  storage-dir: data/uploads/docs
auth:
  token-secret: ${AUTH_TOKEN_SECRET:change-me-please-use-env}
  token-expire-seconds: 86400
# swagger管理：http://localhost:8080/swagger-ui/index.html
