-- Full schema snapshot for the current backend database structure.
-- Non-incremental: execute on a clean database or compare manually before applying to an existing one.

BEGIN;

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(16) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON public.users (username);

CREATE TABLE IF NOT EXISTS public.kb_index_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version VARCHAR(64) NOT NULL,
    embedding_model VARCHAR(255) NOT NULL,
    chunk_count INTEGER NOT NULL DEFAULT 0,
    faiss_path TEXT NOT NULL,
    bm25_path TEXT NOT NULL,
    built_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    active BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX IF NOT EXISTS kb_index_version_version_key ON public.kb_index_version (version);
CREATE UNIQUE INDEX IF NOT EXISTS uq_kb_index_version_active_true
    ON public.kb_index_version (active) WHERE active = TRUE;

CREATE TABLE IF NOT EXISTS public.chat_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_chat_session_user
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_chat_session_user_id ON public.chat_session (user_id);
CREATE INDEX IF NOT EXISTS idx_chat_session_updated_at ON public.chat_session (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_session_user_deleted ON public.chat_session (user_id, deleted);

CREATE TABLE IF NOT EXISTS public.docs (
    doc_id VARCHAR(128) PRIMARY KEY,
    title VARCHAR(512) NOT NULL,
    source VARCHAR(512),
    upload_time VARCHAR(64),
    version VARCHAR(64),
    hash VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT '未处理',
    chunk_count INTEGER NOT NULL DEFAULT 0,
    user_id BIGINT,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    category VARCHAR(100) NOT NULL DEFAULT 'default',
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_docs_user
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_docs_title ON public.docs (title);
CREATE INDEX IF NOT EXISTS idx_docs_upload_time ON public.docs (upload_time);
CREATE INDEX IF NOT EXISTS idx_docs_status ON public.docs (status);
CREATE INDEX IF NOT EXISTS idx_docs_user_id ON public.docs (user_id);
CREATE INDEX IF NOT EXISTS idx_docs_is_default ON public.docs (is_default);
CREATE INDEX IF NOT EXISTS idx_docs_user_default_deleted ON public.docs (user_id, is_default, deleted);
CREATE INDEX IF NOT EXISTS idx_docs_category ON public.docs (category);
CREATE INDEX IF NOT EXISTS idx_docs_deleted ON public.docs (deleted);

CREATE TABLE IF NOT EXISTS public.job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    progress INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_job_type CHECK (type IN ('REINDEX', 'RELOAD')),
    CONSTRAINT ck_job_status CHECK (status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED')),
    CONSTRAINT ck_job_progress_range CHECK (progress >= 0 AND progress <= 100)
);

CREATE INDEX IF NOT EXISTS idx_job_status ON public.job (status);
CREATE INDEX IF NOT EXISTS idx_job_created_at ON public.job (created_at DESC);

CREATE TABLE IF NOT EXISTS public.chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL,
    content TEXT NOT NULL,
    trace_id VARCHAR(128),
    refused BOOLEAN NOT NULL DEFAULT FALSE,
    kb_index_version_id BIGINT,
    retrieval_ms INTEGER NOT NULL DEFAULT 0,
    rerank_ms INTEGER NOT NULL DEFAULT 0,
    gen_ms INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_chat_message_role CHECK (role IN ('user', 'assistant')),
    CONSTRAINT ck_chat_message_timings_nonneg CHECK (
        retrieval_ms >= 0 AND rerank_ms >= 0 AND gen_ms >= 0
    ),
    CONSTRAINT fk_chat_message_session
        FOREIGN KEY (session_id) REFERENCES public.chat_session(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_message_kb_index_version
        FOREIGN KEY (kb_index_version_id) REFERENCES public.kb_index_version(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_chat_message_session_id ON public.chat_message (session_id);
CREATE INDEX IF NOT EXISTS idx_chat_message_trace_id ON public.chat_message (trace_id);
CREATE INDEX IF NOT EXISTS idx_chat_message_created_at ON public.chat_message (created_at DESC);

CREATE TABLE IF NOT EXISTS public.chat_citation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    chunk_id VARCHAR(256) NOT NULL,
    source VARCHAR(512) NOT NULL,
    page INTEGER,
    section VARCHAR(512),
    score DOUBLE PRECISION,
    snippet TEXT,
    CONSTRAINT ck_chat_citation_page_nonneg CHECK (page IS NULL OR page >= 0),
    CONSTRAINT fk_chat_citation_message
        FOREIGN KEY (message_id) REFERENCES public.chat_message(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_chat_citation_message_id ON public.chat_citation (message_id);
CREATE INDEX IF NOT EXISTS idx_chat_citation_chunk_id ON public.chat_citation (chunk_id);

CREATE TABLE IF NOT EXISTS public.job_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    ts TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    level VARCHAR(16) NOT NULL,
    message TEXT NOT NULL,
    CONSTRAINT ck_job_log_level CHECK (level IN ('DEBUG', 'INFO', 'WARN', 'ERROR')),
    CONSTRAINT fk_job_log_job
        FOREIGN KEY (job_id) REFERENCES public.job(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_job_log_job_id ON public.job_log (job_id);
CREATE INDEX IF NOT EXISTS idx_job_log_ts ON public.job_log (ts DESC);

CREATE TABLE IF NOT EXISTS public.system_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    user_id BIGINT,
    username VARCHAR(64),
    user_role VARCHAR(16),
    visibility_scope VARCHAR(16) NOT NULL DEFAULT 'PRIVATE',
    module VARCHAR(32) NOT NULL,
    source VARCHAR(32) NOT NULL,
    action VARCHAR(128) NOT NULL,
    level VARCHAR(16) NOT NULL,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    message VARCHAR(500) NOT NULL,
    details_json TEXT,
    resource_type VARCHAR(64),
    resource_id VARCHAR(128),
    http_method VARCHAR(16),
    request_path VARCHAR(255),
    status_code INTEGER,
    client_ip VARCHAR(64),
    duration_ms BIGINT,
    exception_class VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    CONSTRAINT ck_system_log_scope CHECK (visibility_scope IN ('PRIVATE', 'SYSTEM')),
    CONSTRAINT ck_system_log_level CHECK (level IN ('DEBUG', 'INFO', 'WARN', 'ERROR')),
    CONSTRAINT fk_system_log_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_system_log_created_at ON public.system_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_log_user_created_at ON public.system_log (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_log_trace_id ON public.system_log (trace_id);
CREATE INDEX IF NOT EXISTS idx_system_log_module_created_at ON public.system_log (module, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_log_level_created_at ON public.system_log (level, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_log_scope_created_at ON public.system_log (visibility_scope, created_at DESC);

COMMIT;
